version: "3.2"
services:
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  engine:
    build: engine
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    command: ["./wait_for_mysql.sh", "mysql", "3306", "qwerty", "root", "flask run --host=0.0.0.0"]
