version: "3.9"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1

  engine:
    build: engine
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 5000:5000
    command: ["./wait_for_mysql.sh", "localhost", "3306", "1", "python3", "sql_db.py"]


