version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 8083:3306
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  engine:
    build: engine
    depends_on:
      - mysql
    links:
      - mysql
    command: ["./wait_for_mysql.sh", "mysql", "3306", "qwerty", "social_net", "python3", "sql.py"]
